# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('stage_name', models.CharField(blank=True, max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisualUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageArtwork',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visualAdmin.Artwork')),
                ('file', models.FileField(upload_to='image/')),
            ],
            bases=('visualAdmin.artwork',),
        ),
        migrations.CreateModel(
            name='SoundArtwork',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visualAdmin.Artwork')),
                ('length', models.IntegerField(blank=True, verbose_name='Length (in seconds) : ')),
                ('file', models.FileField(upload_to='audio/')),
            ],
            bases=('visualAdmin.artwork',),
        ),
        migrations.CreateModel(
            name='VideoArtwork',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visualAdmin.Artwork')),
                ('length', models.IntegerField(blank=True, verbose_name='Length (in seconds) :')),
                ('file', models.FileField(upload_to='video/')),
            ],
            bases=('visualAdmin.artwork',),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(to='visualAdmin.Tag'),
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(to='visualAdmin.Tag'),
        ),
    ]
