# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('stage_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
