# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0003_imageartwork_soundartwork_videoartwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='imageartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AlterField(
            model_name='imageartwork',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imageartwork',
            name='publication_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='Length (in seconds) : '),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='publication_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='Length (in seconds) :'),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='publication_date',
            field=models.DateField(blank=True),
        ),
    ]
