# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0003_auto_20160616_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbViews', models.IntegerField(default=0)),
                ('deliveryTime', models.TimeField(blank=True, null=True)),
                ('hasArrived', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualAdmin.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('expo_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('author', models.CharField(blank=True, max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('artworks', models.ManyToManyField(through='visualAdmin.Display', to='visualAdmin.Artwork')),
            ],
        ),
        migrations.AddField(
            model_name='display',
            name='exposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualAdmin.Exposition'),
        ),
    ]
