# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0004_auto_20160605_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AlterField(
            model_name='imageartwork',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
