# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('visualAdmin', '0004_auto_20160705_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_visualadmin.artwork_set+', to='contenttypes.ContentType'),
        ),
    ]
