# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0005_auto_20160605_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='imageartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='file',
            field=models.FileField(upload_to=b'audio/'),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='artists',
            field=models.ManyToManyField(to='visualAdmin.Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(to='visualAdmin.Tag'),
        ),
        migrations.AddField(
            model_name='imageartwork',
            name='tags',
            field=models.ManyToManyField(to='visualAdmin.Tag'),
        ),
        migrations.AddField(
            model_name='soundartwork',
            name='tags',
            field=models.ManyToManyField(to='visualAdmin.Tag'),
        ),
        migrations.AddField(
            model_name='videoartwork',
            name='tags',
            field=models.ManyToManyField(to='visualAdmin.Tag'),
        ),
    ]
