# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0006_auto_20160705_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageArtwork',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visualAdmin.Artwork')),
                ('file', models.FileField(upload_to='image/')),
            ],
            options={
                'abstract': False,
            },
            bases=('visualAdmin.artwork',),
        ),
        migrations.CreateModel(
            name='SoundArtwork',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visualAdmin.Artwork')),
                ('length', models.IntegerField(blank=True, verbose_name='Length (in seconds) : ')),
                ('file', models.FileField(upload_to='audio/')),
            ],
            options={
                'abstract': False,
            },
            bases=('visualAdmin.artwork',),
        ),
        migrations.CreateModel(
            name='VideoArtwork',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visualAdmin.Artwork')),
                ('length', models.IntegerField(blank=True, verbose_name='Length (in seconds) :')),
                ('file', models.FileField(upload_to='video/')),
            ],
            options={
                'abstract': False,
            },
            bases=('visualAdmin.artwork',),
        ),
    ]
