# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0007_imageartwork_soundartwork_videoartwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
