# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0008_auto_20160705_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualAdmin.Exposition')),
            ],
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='Length (in seconds)'),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='Length (in seconds)'),
        ),
        migrations.AddField(
            model_name='visualuser',
            name='tasks',
            field=models.ManyToManyField(to='visualAdmin.Task'),
        ),
    ]
