# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0010_auto_20160706_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Pseudonyme'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, verbose_name="Description de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=255, verbose_name="Titre de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='display',
            name='deliveryTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='display',
            name='hasArrived',
            field=models.BooleanField(default=False, verbose_name='Arrivée'),
        ),
        migrations.AlterField(
            model_name='display',
            name='nbViews',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='author',
            field=models.CharField(blank=True, max_length=64, verbose_name="Auteur de l'exposition"),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='end_date',
            field=models.DateField(verbose_name="Fin de l'exposition"),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='start_date',
            field=models.DateField(verbose_name="Début de l'exposition"),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='title',
            field=models.CharField(max_length=64, verbose_name="Titre de l'exposition"),
        ),
        migrations.AlterField(
            model_name='imageartwork',
            name='file',
            field=models.FileField(upload_to='image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='file',
            field=models.FileField(upload_to='audio/', verbose_name='Son'),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='Durée (en secondes)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description de la tâche'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(verbose_name='Fin de la tâche'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom de la tâche'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(verbose_name='Début de la tâche'),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='file',
            field=models.FileField(upload_to='video/', verbose_name='Vidéo'),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='Durée (En secondes)'),
        ),
        migrations.AlterField(
            model_name='visualuser',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Numéro de téléphone'),
        ),
    ]
