# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0011_auto_20160707_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=30, verbose_name='Libellé du tag')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description du tag')),
            ],
            options={
                'db_table': 'visualAdmin_tag_translation',
                'default_permissions': (),
                'managed': True,
                'verbose_name': 'tag Translation',
                'db_tablespace': '',
            },
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tagtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='visualAdmin.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
