# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0012_auto_20160708_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'oeuvre")),
                ('description', models.TextField(blank=True, verbose_name="Description de l'oeuvre")),
            ],
            options={
                'managed': True,
                'verbose_name': 'artwork Translation',
                'db_table': 'visualAdmin_artwork_translation',
                'default_permissions': (),
                'db_tablespace': '',
            },
        ),
        migrations.CreateModel(
            name='DisplayTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(verbose_name='Description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='visualAdmin.Display')),
            ],
            options={
                'managed': True,
                'verbose_name': 'display Translation',
                'db_table': 'visualAdmin_display_translation',
                'default_permissions': (),
                'db_tablespace': '',
            },
        ),
        migrations.CreateModel(
            name='ExpositionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=64, verbose_name="Titre de l'exposition")),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'managed': True,
                'verbose_name': 'exposition Translation',
                'db_table': 'visualAdmin_exposition_translation',
                'default_permissions': (),
                'db_tablespace': '',
            },
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
        migrations.RemoveField(
            model_name='exposition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exposition',
            name='title',
        ),
        migrations.AddField(
            model_name='expositiontranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='visualAdmin.Exposition'),
        ),
        migrations.AddField(
            model_name='artworktranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='visualAdmin.Artwork'),
        ),
        migrations.AlterUniqueTogether(
            name='expositiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='displaytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='artworktranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
