# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0014_auto_20160708_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artiste', 'verbose_name_plural': 'Artistes'},
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'verbose_name': 'Oeuvre', 'verbose_name_plural': 'Oeuvres'},
        ),
        migrations.AlterModelOptions(
            name='artworktranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Oeuvre Translation'},
        ),
        migrations.AlterModelOptions(
            name='display',
            options={'verbose_name': 'Exposé', 'verbose_name_plural': 'Exposés'},
        ),
        migrations.AlterModelOptions(
            name='displaytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Exposé Translation'},
        ),
        migrations.AlterModelOptions(
            name='exposition',
            options={'verbose_name': 'Exposition', 'verbose_name_plural': 'Expositions'},
        ),
        migrations.AlterModelOptions(
            name='expositiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Exposition Translation'},
        ),
        migrations.AlterModelOptions(
            name='imageartwork',
            options={'verbose_name': 'Oeuvre Image', 'verbose_name_plural': 'Oeuvres Image'},
        ),
        migrations.AlterModelOptions(
            name='soundartwork',
            options={'verbose_name': 'Oeuvre Sonore', 'verbose_name_plural': 'Oeuvres Sonore'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tâche', 'verbose_name_plural': 'Tâches'},
        ),
        migrations.AlterModelOptions(
            name='videoartwork',
            options={'verbose_name': 'Oeuvre Vidéo', 'verbose_name_plural': 'Oeuvres Vidéo'},
        ),
        migrations.AlterModelOptions(
            name='visualuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='visualuser',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='visualAdmin.Task'),
        ),
    ]
