# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0016_auto_20160714_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artworks',
            field=models.ManyToManyField(blank=True, to='visualAdmin.Artwork'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='visualAdmin.Tag'),
        ),
    ]
