# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0017_auto_20160714_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
    ]
