# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0018_auto_20160714_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name="Photo de l'Artiste"),
        ),
        migrations.AlterField(
            model_name='imageartwork',
            name='file',
            field=models.ImageField(upload_to='image/', verbose_name='Image'),
        ),
    ]
