# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0019_auto_20160714_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artworks',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualAdmin.Artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='image/', verbose_name="Photo de l'Artiste"),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(blank=True, to='visualAdmin.Tag'),
        ),
    ]
