# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import visualAdmin.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0020_auto_20160718_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoartwork',
            name='file',
            field=models.FileField(upload_to='video/', validators=[visualAdmin.validators.validate_sound_file_extension], verbose_name='Vidéo'),
        ),
    ]
