# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import visualAdmin.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0021_auto_20160718_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Pseudonyme'),
        ),
        migrations.AlterField(
            model_name='soundartwork',
            name='file',
            field=models.FileField(upload_to='audio/', validators=[visualAdmin.validators.validate_sound_file_extension], verbose_name='Son'),
        ),
        migrations.AlterField(
            model_name='videoartwork',
            name='file',
            field=models.FileField(upload_to='video/', validators=[visualAdmin.validators.validate_video_file_extension], verbose_name='Vidéo'),
        ),
    ]
