# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0022_auto_20160718_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualuser',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, to='visualAdmin.VisualUser'),
        ),
    ]
