# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0025_auto_20160719_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display',
            old_name='deliveryTime',
            new_name='delivery_time',
        ),
        migrations.RenameField(
            model_name='display',
            old_name='nbViews',
            new_name='nb_views',
        ),
    ]
