# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0026_auto_20160720_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Emplacement'),
        ),
        migrations.AddField(
            model_name='exposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name="Affiche de l'Exposition"),
        ),
    ]
