# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0027_auto_20160725_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='displaytranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='displaytranslation',
            name='master',
        ),
        migrations.RenameField(
            model_name='display',
            old_name='hasArrived',
            new_name='has_arrived',
        ),
        migrations.RemoveField(
            model_name='display',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='display',
            name='nb_views',
            field=models.IntegerField(default=0, verbose_name='Nombre de consultations'),
        ),
        migrations.DeleteModel(
            name='DisplayTranslation',
        ),
    ]
