# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualAdmin', '0028_auto_20160727_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualAdmin.Artwork', verbose_name='Oeuvre'),
        ),
        migrations.AlterField(
            model_name='display',
            name='exposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualAdmin.Exposition', verbose_name='Exposition'),
        ),
        migrations.AlterField(
            model_name='display',
            name='has_arrived',
            field=models.BooleanField(default=False, verbose_name='Livrée'),
        ),
    ]
